
server:
  port: 8085
  servlet:
    context-path: /api

spring:
  application:
    name: course
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/USER?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root

jwt:
  secret: salomaotokensecret